# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: order_manager_development
  username: order_manager_dev
  password: 123456
  host: localhost
  port: 5432

test:
  <<: *default
  database: order_manager_test
  username: order_manager_dev
  password: 123456
  host: localhost
  port: 5432

production:
  <<: *default
  database: order-manager-api_production
  username: order-manager-api
  password: <%= ENV['ORDER-MANAGER-API_DATABASE_PASSWORD'] %>
